baseurl: /
title: ATU Math
description: Math from the Atlantic Technological University
author: Ian McLoughlin

paginate: 8

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  subtitle: Atlantic Technological University
  twitter: mcianloughlin
  github: ianmcloughlin
  gitlab: ianmcloughlin
  linkedin: mcloughlinian

menu:
  main:
  - identifier: about
    name: about
    url: /about
    weight: 10
  - name: blog
    url: /
    weight: 20
  - name: courses
    url: /courses
    weight: 30
  - name: tags
    url: /tags
    weight: 40
  - name: notebooks
    url: https://nbviewer.org/github/ianmcloughlin/jupyter-teaching-notebooks
    weight: 50
  - name: github
    url: https://github.com/ianmcloughlin
    weight: 60
  

taxonomies:
  tag: tags
  course: courses